import { useEffect, useMemo, useState } from 'react'
import { CalendarDays, Maximize2, RefreshCw } from 'lucide-react'
import { supabase } from './lib/supabase'
import type { ProgrammeImport } from './types'
type LiveState={programme:ProgrammeImport|null}
function rowKey(day:string,session:string){return `${day}::${session}`}
export default function ProgrammeDisplay({onExit}:{onExit:()=>void}){
 const [state,setState]=useState<LiveState>({programme:null});const [now,setNow]=useState(new Date())
 async function load(){const {data}=await supabase.from('app_live_state').select('state').eq('id','main').maybeSingle();if(data?.state)setState(data.state as LiveState)}
 useEffect(()=>{load();const timer=window.setInterval(()=>{setNow(new Date());load()},30000);const channel=supabase.channel('programme-display-live').on('postgres_changes',{event:'*',schema:'public',table:'app_live_state',filter:'id=eq.main'},load).subscribe();return()=>{clearInterval(timer);supabase.removeChannel(channel)}},[])
 const merged=useMemo(()=>{const map=new Map<string,Map<number,string>>();for(const row of state.programme?.rows??[]){const cells=map.get(rowKey(row.day,row.session))??new Map<number,string>();for(const c of row.cells)if(c.activityCode)cells.set(c.group,c.activityCode);map.set(rowKey(row.day,row.session),cells)}return map},[state.programme])
 const rows=useMemo(()=>{const seen=new Set<string>();return (state.programme?.rows??[]).filter(r=>{const k=rowKey(r.day,r.session);if(seen.has(k))return false;seen.add(k);return true})},[state.programme])
 async function fullScreen(){try{await document.documentElement.requestFullscreen()}catch{}}
 return <main className="programme-display-shell"><header className="staff-display-header"><div className="staff-display-brand"><img src={`${import.meta.env.BASE_URL}manor-adventure-logo.png`} alt="Manor Adventure"/><div><p>NORFOLK LAKES</p><h1>Programme Display</h1></div></div><div className="staff-display-date"><CalendarDays/><strong>{state.programme?.title||'No live programme'}</strong><span>{now.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})} · {now.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'})}</span></div><div className="staff-display-actions"><button onClick={()=>void load()}><RefreshCw/>Refresh</button><button onClick={fullScreen}><Maximize2/>Full screen</button><button onClick={onExit}>Exit display</button></div></header>
 {!state.programme?<section className="staff-display-empty"><h2>No programme is live</h2></section>:<section className="programme-tv-scroll"><table className="programme-tv-table"><thead><tr><th className="tv-day">Day</th><th className="tv-session">Ses</th>{state.programme.groupNumbers.map(g=><th key={g}>G{g}<small>{state.programme?.schoolDetails?.find(s=>s.groupNumbers?.includes(g))?.schoolName||''}</small></th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={rowKey(r.day,r.session)} className={i===0||rows[i-1]?.day!==r.day?'tv-day-start':''}><th className="tv-day">{i===0||rows[i-1]?.day!==r.day?r.day:''}</th><th className="tv-session">{r.session}</th>{state.programme!.groupNumbers.map(g=>{const code=merged.get(rowKey(r.day,r.session))?.get(g)||'';return <td key={g} className={`tv-code code-${code.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`}>{code||'—'}</td>})}</tr>)}</tbody></table></section>}<footer className="staff-display-footer">Live read-only programme display · refreshes automatically every 30 seconds</footer></main>
}
